import yfinance as yf
from typing import Final, List

# print(yf.Ticker("AAPL").info)

ticker_methods: List[List[str]] = [['address1'], ['city'], ['state'], ['zip'], 
 ['country'], ['phone'], ['website'], 
 ['industry'], ['industryKey'], 
 ['industryDisp'], ['sector'], ['sectorKey'], 
 ['sectorDisp'], 
 ['fullTimeEmployees'],  
 ['auditRisk'], ['boardRisk'], ['compensationRisk'], ['shareHolderRightsRisk'], 
['overallRisk'], ['governanceEpochDate'], ['compensationAsOfEpochDate'], 
['irWebsite'], 
['previousClose'], ['open'], ['dayLow'], ['dayHigh'], 
['regularMarketPreviousClose'], ['regularMarketOpen'], 
['regularMarketDayLow'], ['regularMarketDayHigh'], ['dividendRate'], 
['dividendYield'], ['exDividendDate'], ['payoutRatio'], 
['fiveYearAvgDividendYield'], ['beta'], ['trailingPE'], ['forwardPE'], 
['volume'], ['regularMarketVolume'], ['averageVolume'], 
['averageVolume10days'], ['averageDailyVolume10Day'], ['bid'], 
['ask'], ['bidSize'], ['askSize'], ['marketCap'], 
['fiftyTwoWeekLow'], ['fiftyTwoWeekHigh'], ['priceToSalesTrailing12Months'], 
['fiftyDayAverage'], ['twoHundredDayAverage'], 
['trailingAnnualDividendRate'], ['trailingAnnualDividendYield'], 
['currency'], ['enterpriseValue'], ['profitMargins'], 
['floatShares'], ['sharesOutstanding'], ['sharesShort'], 
['sharesShortPriorMonth'], ['sharesShortPreviousMonthDate'], 
['dateShortInterest'], ['sharesPercentSharesOut'], 
['heldPercentInsiders'], ['heldPercentInstitutions'], 
['shortRatio'], ['shortPercentOfFloat'], ['impliedSharesOutstanding'], 
['bookValue'], ['priceToBook'], ['lastFiscalYearEnd'], 
['nextFiscalYearEnd'], ['mostRecentQuarter'], 
['earningsQuarterlyGrowth'], ['netIncomeToCommon'], 
['trailingEps'], ['forwardEps'], ['pegRatio'], 
['lastSplitFactor'], ['lastSplitDate'], ['enterpriseToRevenue'], 
['enterpriseToEbitda'], ['52WeekChange'], ['SandP52WeekChange'], 
['lastDividendValue'], ['lastDividendDate'], ['exchange'], 
['quoteType'],
['shortName'], ['longName'], ['firstTradeDateEpochUtc'], 
['timeZoneFullName'], ['timeZoneShortName'], 
['uuid'], ['messageBoardId'], 
['gmtOffSetMilliseconds'], ['currentPrice'], 
['targetHighPrice'], ['targetLowPrice'], ['targetMeanPrice'], 
['targetMedianPrice'], ['recommendationMean'], 
['recommendationKey'], ['numberOfAnalystOpinions'], ['totalCash'], 
['totalCashPerShare'],[ 'ebitda'], ['totalDebt'], 
['quickRatio'], ['currentRatio'], ['totalRevenue'], 
['debtToEquity'], ['revenuePerShare'], ['returnOnAssets'], 
['returnOnEquity'], ['freeCashflow'], 
['operatingCashflow'], ['earningsGrowth'], 
['revenueGrowth'], ['grossMargins'], ['ebitdaMargins'], 
['operatingMargins'], ['financialCurrency'], ['trailingPegRatio']]

print(ticker_methods)


# {'address1': 'One Apple Park Way', 'city': 'Cupertino', 'state': 'CA', 'zip': '95014', 
#  'country': 'United States', 'phone': '408 996 1010', 'website': 'https://www.apple.com', 
#  'industry': 'Consumer Electronics', 'industryKey': 'consumer-electronics', 
#  'industryDisp': 'Consumer Electronics', 'sector': 'Technology', 'sectorKey': 'technology', 
#  'sectorDisp': 'Technology', 
# 'fullTimeEmployees': 150000, 
# 'companyOfficers': [{'maxAge': 1, 'name': 'Mr. Timothy D. Cook', 'age': 62, 'title': 'CEO & Director', 'yearBorn': 1961, 'fiscalYear': 2023, 'totalPay': 16239562, 'exercisedValue': 0, 'unexercisedValue': 0}, 
#                     {'maxAge': 1, 'name': 'Mr. Luca  Maestri', 'age': 60, 'title': 'CFO & Senior VP', 'yearBorn': 1963, 'fiscalYear': 2023, 'totalPay': 4612242, 'exercisedValue': 0, 'unexercisedValue': 0}, 
#                     {'maxAge': 1, 'name': 'Mr. Jeffrey E. Williams', 'age': 59, 'title': 'Chief Operating Officer', 'yearBorn': 1964, 'fiscalYear': 2023, 'totalPay': 4637585, 'exercisedValue': 0, 'unexercisedValue': 0}, 
#                     {'maxAge': 1, 'name': 'Ms. Katherine L. Adams', 'age': 59, 'title': 'Senior VP, General Counsel & Secretary', 'yearBorn': 1964, 'fiscalYear': 2023, 'totalPay': 4618064, 'exercisedValue': 0, 'unexercisedValue': 0}, 
#                     {'maxAge': 1, 'name': "Ms. Deirdre  O'Brien", 'age': 56, 'title': 'Senior Vice President of Retail', 'yearBorn': 1967, 'fiscalYear': 2023, 'totalPay': 4613369, 'exercisedValue': 0, 'unexercisedValue': 0}, 
#                     {'maxAge': 1, 'name': 'Mr. Chris  Kondo', 'title': 'Senior Director of Corporate Accounting', 'fiscalYear': 2023, 'exercisedValue': 0, 'unexercisedValue': 0}, 
#                     {'maxAge': 1, 'name': 'Mr. James  Wilson', 'title': 'Chief Technology Officer', 'fiscalYear': 2023, 'exercisedValue': 0, 'unexercisedValue': 0}, 
#                     {'maxAge': 1, 'name': 'Suhasini  Chandramouli', 'title': 'Director of Investor Relations', 'fiscalYear': 2023, 'exercisedValue': 0, 'unexercisedValue': 0}, 
#                     {'maxAge': 1, 'name': 'Mr. Greg  Joswiak', 'title': 'Senior Vice President of Worldwide Marketing', 'fiscalYear': 2023, 'exercisedValue': 0, 'unexercisedValue': 0}, 
#                     {'maxAge': 1, 'name': 'Mr. Adrian  Perica', 'age': 49, 'title': 'Head of Corporate Development', 'yearBorn': 1974, 'fiscalYear': 2023, 'exercisedValue': 0, 'unexercisedValue': 0}], 
#                     'auditRisk': 6, 'boardRisk': 1, 'compensationRisk': 2, 'shareHolderRightsRisk': 1, 
#                     'overallRisk': 1, 'governanceEpochDate': 1717200000, 'compensationAsOfEpochDate': 1703980800, 
#                     'irWebsite': 'http://investor.apple.com/', 'maxAge': 86400, 'priceHint': 2, 
#                     'previousClose': 213.25, 'open': 214.63, 'dayLow': 212.35, 'dayHigh': 215.7395, 
#                     'regularMarketPreviousClose': 213.25, 'regularMarketOpen': 214.63, 
#                     'regularMarketDayLow': 212.35, 'regularMarketDayHigh': 215.7395, 'dividendRate': 1.0, 
#                     'dividendYield': 0.0047, 'exDividendDate': 1715299200, 'payoutRatio': 0.14930001, 
#                     'fiveYearAvgDividendYield': 0.71, 'beta': 1.25, 'trailingPE': 33.34891, 'forwardPE': 29.369, 
#                     'volume': 49566822, 'regularMarketVolume': 49566822, 'averageVolume': 68123254, 
#                     'averageVolume10days': 92762300, 'averageDailyVolume10Day': 92762300, 'bid': 213.87, 
#                     'ask': 213.95, 'bidSize': 100, 'askSize': 200, 'marketCap': 3283030900736, 
#                     'fiftyTwoWeekLow': 164.08, 'fiftyTwoWeekHigh': 220.2, 'priceToSalesTrailing12Months': 8.602812, 
#                     'fiftyDayAverage': 189.8298, 'twoHundredDayAverage': 183.52425, 
#                     'trailingAnnualDividendRate': 0.96, 'trailingAnnualDividendYield': 0.0045017586, 
#                     'currency': 'USD', 'enterpriseValue': 3320466898944, 'profitMargins': 0.26306, 
#                     'floatShares': 15308474083, 'sharesOutstanding': 15334099968, 'sharesShort': 153405579, 
#                     'sharesShortPriorMonth': 99287450, 'sharesShortPreviousMonthDate': 1715731200, 
#                     'dateShortInterest': 1718323200, 'sharesPercentSharesOut': 0.01, 
#                     'heldPercentInsiders': 0.052199997, 'heldPercentInstitutions': 0.57608, 
#                     'shortRatio': 2.29, 'shortPercentOfFloat': 0.01, 'impliedSharesOutstanding': 15334099968, 
#                     'bookValue': 4.837, 'priceToBook': 44.262974, 'lastFiscalYearEnd': 1696032000, 
#                     'nextFiscalYearEnd': 1727654400, 'mostRecentQuarter': 1711756800, 
#                     'earningsQuarterlyGrowth': -0.022, 'netIncomeToCommon': 100389003264, 
#                     'trailingEps': 6.42, 'forwardEps': 7.29, 'pegRatio': 3.08, 
#                     'lastSplitFactor': '4:1', 'lastSplitDate': 1598832000, 'enterpriseToRevenue': 8.701, 
#                     'enterpriseToEbitda': 25.615, '52WeekChange': 0.10377896, 'SandP52WeekChange': 0.23200047, 
#                     'lastDividendValue': 0.25, 'lastDividendDate': 1715299200, 'exchange': 'NMS', 
#                     'quoteType': 'EQUITY', 'symbol': 'AAPL', 'underlyingSymbol': 'AAPL', 
#                     'shortName': 'Apple Inc.', 'longName': 'Apple Inc.', 'firstTradeDateEpochUtc': 345479400, 
#                     'timeZoneFullName': 'America/New_York', 'timeZoneShortName': 'EDT', 
#                     'uuid': '8b10e4ae-9eeb-3684-921a-9ab27e4d87aa', 'messageBoardId': 'finmb_24937', 
#                     'gmtOffSetMilliseconds': -14400000, 'currentPrice': 214.1, 
#                     'targetHighPrice': 275.0, 'targetLowPrice': 164.0, 'targetMeanPrice': 211.8, 
#                     'targetMedianPrice': 210.0, 'recommendationMean': 2.0, 
#                     'recommendationKey': 'buy', 'numberOfAnalystOpinions': 37, 'totalCash': 67150000128, 
#                     'totalCashPerShare': 4.379, 'ebitda': 129629003776, 'totalDebt': 104590000128, 
#                     'quickRatio': 0.875, 'currentRatio': 1.037, 'totalRevenue': 381623009280, 
#                     'debtToEquity': 140.968, 'revenuePerShare': 24.537, 'returnOnAssets': 0.22073999, 
#                     'returnOnEquity': 1.4725, 'freeCashflow': 84726874112, 
#                     'operatingCashflow': 110563000320, 'earningsGrowth': 0.007, 
#                     'revenueGrowth': -0.043, 'grossMargins': 0.45586, 'ebitdaMargins': 0.33968, 
#                     'operatingMargins': 0.30743, 'financialCurrency': 'USD', 'trailingPegRatio': 2.266}
